#requires -Version 5.1
<#
.SYNOPSIS
  Build a portable Context Vocab extension with API keys baked in.

.DESCRIPTION
  Prompts for your DeepSeek API key and Eudic Bearer token, then produces
  context-vocab-portable.zip in the repo root. The zip contains a single
  top-level folder `context-vocab/` that you can unzip on any computer and
  load via chrome://extensions -> Load unpacked, with no further setup.

  The working tree's src/preset.json is NEVER modified — keys only live
  inside the zip. This means you can build a portable bundle from a clone
  of the public repo without risking a key leak via `git push`.

.NOTES
  Anyone with a filled-in copy of the resulting zip has full access to
  your DeepSeek and Eudic accounts. Treat it like a password file.
#>

[CmdletBinding()]
param(
  [string]$DeepSeekKey,
  [string]$EudicToken,
  [string]$OutputZip
)

$ErrorActionPreference = "Stop"

$root = $PSScriptRoot
if (-not $root) { $root = (Get-Location).Path }
$zipPath = if ($OutputZip) { $OutputZip } else { Join-Path $root "context-vocab-portable.zip" }

Write-Host ""
Write-Host "Context Vocab — 便携模式打包" -ForegroundColor Cyan
Write-Host "----------------------------------------"
Write-Host ""
Write-Host "⚠️  生成的 zip 会包含你的 API key（明文）。" -ForegroundColor Yellow
Write-Host "    任何拿到 zip 的人都能用你的 DeepSeek + 欧陆账号。"
Write-Host "    不要发到公开网络（GitHub / 微博 / 公开群聊）。"
Write-Host "    建议优盘 / 私聊 / 自己邮箱 之间传递。"
Write-Host ""

if (-not $DeepSeekKey) {
  $DeepSeekKey = Read-Host "DeepSeek API Key (sk-...)"
}
if (-not $EudicToken) {
  $EudicToken = Read-Host "欧陆 OpenAPI Token (粘贴原始 token，无 Bearer 前缀)"
}

$DeepSeekKey = $DeepSeekKey.Trim()
$EudicToken  = $EudicToken.Trim()

if (-not $DeepSeekKey -and -not $EudicToken) {
  Write-Host "两个 key 都为空，没必要打包便携版。" -ForegroundColor Red
  exit 1
}

# Stage in TEMP so the working tree is never touched.
$staging = Join-Path ([System.IO.Path]::GetTempPath()) ("context-vocab-build-" + [guid]::NewGuid())
$inner   = Join-Path $staging "context-vocab"
New-Item -ItemType Directory -Path $inner -Force | Out-Null

try {
  # Copy the bits Chrome actually needs to run the extension.
  Copy-Item -Path (Join-Path $root "manifest.json") -Destination $inner
  Copy-Item -Path (Join-Path $root "src")           -Destination $inner -Recurse
  Copy-Item -Path (Join-Path $root "icons")         -Destination $inner -Recurse

  # Bake keys into the staged preset.json (NOT the working tree's).
  $stagedPreset = Join-Path $inner "src\preset.json"
  $presetObj = [ordered]@{
    "_comment"     = "Portable build. Generated by make-portable.ps1. Do not commit."
    "deepseek_key" = $DeepSeekKey
    "eudic_token"  = $EudicToken
  }
  ($presetObj | ConvertTo-Json -Depth 4) | Set-Content -Path $stagedPreset -Encoding UTF8

  # Zip it. -Path on a directory packs it as a top-level folder in the zip.
  if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
  Compress-Archive -Path $inner -DestinationPath $zipPath -Force

  $size = (Get-Item $zipPath).Length
  Write-Host ""
  Write-Host "✅ 打包完成:" -ForegroundColor Green
  Write-Host ("   {0}" -f $zipPath)
  Write-Host ("   {0:N1} KB" -f ($size / 1KB))
  Write-Host ""
  Write-Host "在公用电脑上的使用流程:" -ForegroundColor Cyan
  Write-Host "  1. 把 zip 拷到优盘 / 微信发到目标电脑"
  Write-Host "  2. 解压到任意位置（会得到 context-vocab/ 文件夹）"
  Write-Host "  3. Chrome 打开 chrome://extensions"
  Write-Host "  4. 右上角开启「开发者模式」"
  Write-Host "  5. 点「加载已解压的扩展程序」选解压后的 context-vocab 文件夹"
  Write-Host "  6. 直接划词查词，API key 已自动写入"
  Write-Host ""
  Write-Host "用完后:" -ForegroundColor Cyan
  Write-Host "  chrome://extensions → 找到 Context Vocab → 点「移除」"
  Write-Host "  这样会一并清掉 chrome.storage.local 里的 key，不会留在公用电脑上"
  Write-Host ""
  Write-Host "工作树状态:" -ForegroundColor DarkGray
  Write-Host "  src/preset.json 没有被修改（仍是空 key）"
  Write-Host "  $zipPath 已加进 .gitignore，不会被 git 追踪"
}
finally {
  if (Test-Path $staging) { Remove-Item $staging -Recurse -Force }
}
